server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
    basedir: logs/tomcat
    accesslog:
      enabled: true
      pattern: '%h %A %S %t "%r" %s %b %D'
    max-threads: 500
    max-connections: 500

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dmo_exam?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 192.168.106.4
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: -1
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 3000


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.exam.model.entity